---
- name: Create user and add to sudoers
  hosts: all
  become: true

  vars_prompt:
    - name: "username"
      prompt: "Enter the username for the management shell account:"
      private: no
    - name: "password"
      prompt: "Enter the password for the management shell account:"
      private: yes

  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_file: .ssh/{{ username }}
        password: "{{ password | password_hash('sha512') }}"

    - name: create /etc/sudoers.d/User file
      file:
        path: /etc/sudoers.d/{{ username }}
        state: touch

    - name: configure a pass-wordless authentication & execution for User
      lineinfile:
        path: /etc/sudoers.d/{{ username }}
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        state: present

    - name: install the SSH public key on managed host for User
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/kasius/.ssh/{{ username }}.pub') }}"

